import type { Metadata } from "next";
import { Ovo, Poppins, Roboto_Flex } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const ovo = Ovo({
  variable: "--font-ovo",
  subsets: ["latin"],
  weight: "400",
});

const sansCustom = Roboto_Flex({
  variable: "--font-sans-custom",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ovo.variable} ${sansCustom.variable} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
